[project]
name = "nano-qwen3tts-vllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "qwen-tts>=0.0.5",
    "torch>=2.10.0",
    "transformers>=4.57.3",
]
